import type { Metadata } from "next";
import { Cpu, Bot, Zap, ShieldCheck, Ticket, Users, BarChart3, CheckCircle2 } from "lucide-react";
import SEOPage from "@/components/landing/SEOPage";

export const metadata: Metadata = {
  title: "AI Event Management Platform & Autonomous MCP Operations | URPASS",
  description:
    "The world's first AI-native event management platform. Built-in Model Context Protocol (MCP) server for Claude Desktop, Cursor, and autonomous AI agent operations.",
  keywords: [
    "ai event management platform",
    "ai event ticketing",
    "model context protocol event management",
    "autonomous event check in",
    "mcp ticketing platform",
    "ai attendee screening",
  ],
  alternates: { canonical: "https://urpass.space/ai-event-management-platform" },
  openGraph: {
    title: "AI Event Management Platform & Autonomous MCP Operations | URPASS",
    description: "The world's first AI-native event platform with Model Context Protocol support.",
    url: "https://urpass.space/ai-event-management-platform",
    locale: "en_IN",
    type: "website",
  },
};

export default function Page() {
  return (
    <SEOPage
      config={{
        badge: "AI & AGENTIC ARCHITECTURE",
        h1: "AI Event Management Platform & Model Context Protocol Operations",
        canonicalUrl: "https://urpass.space/ai-event-management-platform",
        description:
          "Manage events, approve attendees, issue passes, and query gate check-in velocity through conversational AI. Native Model Context Protocol (MCP) server for Claude and Cursor.",
        ctaLabel: "Connect AI Agent Free",
        directAnswer: {
          title: "How Does the URPASS AI Event Management Platform Work?",
          summary:
            "URPASS is the first event infrastructure platform designed for agentic AI. By supporting Anthropic's Model Context Protocol (MCP), URPASS exposes 10 production tools enabling Large Language Models (in Claude Desktop, Cursor IDE, or custom autonomous agents) to query event attendance, filter applicant rosters, issue cryptographic passes, and monitor entrance velocity using natural language prompts.",
          keyPoints: [
            "Native Model Context Protocol (MCP) server conforming to open standard v1.0.0",
            "10 production-ready AI tools: event stats, attendee filtering, approval/rejection, and pass issuance",
            "Local stdio CLI execution (`npx urpass-mcp`) and remote HTTPS JSON-RPC 2.0 (`/api/mcp`)",
            "Zero per-ticket platform commission fees with transparent flat software pricing and ₹0 free tier",
          ],
        },
        keyFactsTable: {
          title: "AI & Model Context Protocol Capabilities",
          subtitle: "Technical specifications of URPASS AI agent integration.",
          headers: ["AI Capability", "URPASS Implementation", "Legacy Ticketing Tools"],
          rows: [
            { col1: "Model Context Protocol (MCP)", col2: "Native stdio CLI (`npx urpass-mcp`) & HTTPS `/api/mcp`", col3: "No native MCP support" },
            { col1: "Supported AI Clients", col2: "Claude Desktop, Cursor IDE, LangChain, CrewAI", col3: "Limited or unsupported" },
            { col1: "Production MCP Tools", col2: "10 tools for event stats, attendees, screening, passes", col3: "Zero conversational tools" },
            { col1: "Conversational Roster Queries", col2: "\"Show me how many VIPs checked in from Google\"", col3: "Manual filtering across complex dashboards" },
            { col1: "Automated Candidate Screening", col2: "AI agents evaluate criteria and call `approve_attendee`", col3: "Manual line-by-line review only" },
          ],
        },
        features: [
          { icon: Bot, title: "Conversational Event Management", desc: "Ask Claude Desktop or Cursor 'How is check-in velocity at Gate 1?' and receive instant, live database answers." },
          { icon: Cpu, title: "10 Production MCP Tools", desc: "Query events, inspect ticket tier capacities, screen applicant responses, and issue passes via natural language." },
          { icon: Zap, title: "Autonomous Pass Issuance", desc: "Automate screening workflows where your AI agent reviews candidate backgrounds and dispatches passes automatically." },
          { icon: ShieldCheck, title: "Cryptographic Single-Use Tokens", desc: "Passes generated by AI agents inherit the exact same atomic anti-duplicate locks and sub-0.3s camera verification." },
          { icon: Users, title: "Autonomous Attendee Screening", desc: "Screen hackathon or conference applicants by prompting your agent to verify GitHub portfolios or LinkedIn credentials." },
          { icon: BarChart3, title: "Real-Time Telemetry Streaming", desc: "Feed live arrival velocity numbers into your AI assistant for automated post-event summary reports." },
        ],
        steps: [
          { n: "01", title: "Generate API Key", desc: "Create a secure API key in your URPASS organizer developer dashboard." },
          { n: "02", title: "Configure Claude or Cursor", desc: "Add the `urpass` server command (`npx -y urpass-mcp`) to your configuration file." },
          { n: "03", title: "Interact with Events", desc: "Ask your AI assistant to list active events, summarize ticket sales, or search attendees." },
          { n: "04", title: "Automate Approvals", desc: "Prompt your agent to review applications and call `approve_attendee` for qualified guests." },
          { n: "05", title: "Stream Gate Metrics", desc: "Ask for live gate turnout statistics during the event for instant status reports." },
        ],
        callout: {
          badge: "AGENTIC FUTURE",
          title: "The first event management platform designed for the AI era.",
          description: "Stop wasting hours clicking through administrative forms. Connect your AI agent to URPASS and delegate attendee screening, ticket queries, and post-event analytics to conversational assistants.",
          bullets: [
            "Conforms to Anthropic's open Model Context Protocol (MCP) standard",
            "Works with Claude Desktop, Cursor IDE, and custom autonomous agents",
            "Zero per-ticket percentage cuts with flat software pricing",
            "Permanent Free Tier available for community events up to 100 registrations",
          ],
        },
        faqs: [
          { q: "What is Model Context Protocol (MCP)?", a: "Model Context Protocol is an open standard developed by Anthropic that allows AI assistants (like Claude) to securely connect to external tools, databases, and APIs. URPASS uses MCP to let AI manage events directly." },
          { q: "How do I install the URPASS MCP server?", a: "You can run it locally with `npx -y urpass-mcp` or connect cloud agents to the HTTPS JSON-RPC endpoint at `https://urpass.space/api/mcp` with your API key." },
          { q: "Can an AI agent approve attendee applications for me?", a: "Yes. Using the `approve_attendee` tool, an AI agent can evaluate registration form responses against your criteria and approve qualified attendees, automatically dispatching their QR pass." },
          { q: "Does using MCP cost extra on URPASS?", a: "No. The MCP server is available across all URPASS tiers, including the permanent Free Tier." },
        ],
        relatedLinks: [
          { title: "Model Context Protocol Hub", href: "/mcp-event-management", category: "Product" },
          { title: "Claude Desktop Event Ops", href: "/claude-desktop-event-management", category: "Product" },
          { title: "Cursor MCP Ticketing", href: "/cursor-mcp-event-ticketing", category: "Product" },
          { title: "MCP Server Specification", href: "/mcp-server-for-events", category: "Product" },
        ],
      }}
    />
  );
}
