import type { Metadata } from "next";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import FreeTicketGenerator from "@/components/playground/FreeTicketGenerator";
import Link from "next/link";
import {
  QrCode,
  Sparkles,
  CheckCircle2,
  ShieldCheck,
  ScanLine,
  Layers,
  Percent,
  Smartphone,
  ArrowRight,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Free QR Ticket Generator: Create Digital Event Passes | URPASS",
  description:
    "Design and generate custom QR event tickets online for free. Interactive ticket studio, downloadable passes, and sub-0.3s mobile browser gate check-in.",
  keywords: [
    "free qr ticket generator",
    "event qr code generator",
    "how to create qr tickets for an event",
    "online ticket maker with qr code",
    "digital event pass generator",
    "free event ticketing platform",
    "single use qr codes for events",
  ],
  alternates: {
    canonical: "https://urpass.space/free-qr-ticket-generator",
  },
  openGraph: {
    title: "Free QR Ticket Generator: Create Digital Event Passes | URPASS",
    description:
      "Design and generate custom QR event tickets online for free. Sub-0.3s mobile camera scanning, 0% ticket commissions, and instant pass delivery.",
    url: "https://urpass.space/free-qr-ticket-generator",
    locale: "en_IN",
    type: "website",
  },
};

const FAQS = [
  {
    q: "Can I generate free QR tickets for my event on URPASS?",
    a: "Yes. URPASS offers a permanent ₹0 Free Tier that allows organizers to create up to 2 active events per month and issue up to 100 free digital QR tickets per month. No credit card is required to sign up or publish your event.",
  },
  {
    q: "How does the QR ticket prevent unauthorized duplicate entry?",
    a: "Every pass generated by URPASS contains a unique, cryptographically signed UUID token mapped to your event's attendee manifest. When scanned at venue gates, an atomic database transaction marks the pass as checked-in. If the attendee shares a screenshot of the pass, other gate scanners will immediately display a red duplicate alert with the exact initial check-in timestamp.",
  },
  {
    q: "Do gate volunteers need to install an app to scan these tickets?",
    a: "No. Unlike legacy systems that require downloading specialized apps from the App Store or Google Play, URPASS gate scanners run natively inside any mobile browser (Safari, Chrome). Volunteers simply open a secure PIN-verified scanner link and scan in under 0.3 seconds.",
  },
  {
    q: "Can attendees save their QR passes to Apple Wallet or mobile devices?",
    a: "Yes. URPASS digital passes are mobile-responsive web passes formatted for easy bookmarking, screenshotting, and Apple Wallet layout integration. Passes can also be downloaded directly as high-resolution PNG images.",
  },
  {
    q: "Can I collect payments for paid tickets on URPASS?",
    a: "Yes. URPASS integrates directly with Razorpay (supporting PhonePe, Google Pay, Paytm, UPI QR, and cards) and Stripe with 0% platform commission. You keep 100% of your ticket revenue.",
  },
];

export default function FreeTicketGeneratorPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQS.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: f.a,
      },
    })),
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://urpass.space" },
      { "@type": "ListItem", position: 2, name: "Free QR Ticket Generator", item: "https://urpass.space/free-qr-ticket-generator" },
    ],
  };

  return (
    <div className="min-h-screen bg-neutral-50 text-neutral-900 flex flex-col justify-between selection:bg-violet-100 selection:text-violet-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <div>
        <Navbar />

        {/* Hero & Interactive Playground */}
        <section className="pt-32 pb-16 sm:pt-40 sm:pb-20 px-5 sm:px-8 border-b border-neutral-200/80 bg-white">
          <div className="max-w-4xl mx-auto text-center mb-10 sm:mb-12">
            <div className="inline-flex items-center gap-2 bg-violet-50 border border-violet-100 text-violet-700 text-xs font-semibold px-3.5 py-1.5 rounded-full mb-4">
              <QrCode className="w-3.5 h-3.5" />
              FREE IN-BROWSER TICKET MAKER
            </div>
            <h1 className="text-3xl sm:text-5xl font-black text-neutral-950 tracking-tight leading-tight">
              Free QR Ticket Generator for Events
            </h1>
            <p className="mt-4 text-base sm:text-lg text-neutral-600 max-w-2xl mx-auto leading-relaxed">
              Design custom branded passes, preview live scannable QR tokens, and publish your event registration page in under 30 seconds.
            </p>
          </div>

          {/* Interactive Playground Component */}
          <FreeTicketGenerator />
        </section>

        {/* How It Works 3-Step Process */}
        <section className="py-16 sm:py-24 px-5 sm:px-8 max-w-5xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-14">
            <h2 className="text-2xl sm:text-3xl font-black text-neutral-950">
              From Registration to Door Scan in 3 Steps
            </h2>
            <p className="text-xs sm:text-sm text-neutral-500 mt-2">
              Automate your entire ticketing workflow without printing paper badges or renting barcode hardware.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-2xl border border-neutral-200 shadow-xs relative">
              <span className="text-3xl font-black text-violet-600 font-mono mb-2 block">01</span>
              <h3 className="text-base font-bold text-neutral-900">Publish Your Link</h3>
              <p className="text-xs text-neutral-600 mt-2 leading-relaxed">
                Create your event, set ticket classes (VIP, General, Free, Paid), and share your mobile-responsive registration page across WhatsApp and social media.
              </p>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-neutral-200 shadow-xs relative">
              <span className="text-3xl font-black text-violet-600 font-mono mb-2 block">02</span>
              <h3 className="text-base font-bold text-neutral-900">Auto-Deliver QR Passes</h3>
              <p className="text-xs text-neutral-600 mt-2 leading-relaxed">
                As soon as an attendee registers or completes UPI payment, URPASS dynamically generates and delivers a personalized cryptographic QR pass via email and web link.
              </p>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-neutral-200 shadow-xs relative">
              <span className="text-3xl font-black text-violet-600 font-mono mb-2 block">03</span>
              <h3 className="text-base font-bold text-neutral-900">Scan in &lt;0.3s at Doors</h3>
              <p className="text-xs text-neutral-600 mt-2 leading-relaxed">
                Gate volunteers open a secure scanner URL on their own phones (Safari, Chrome). Passes scan at lightning speed with loud audible chimes and anti-duplicate lockout.
              </p>
            </div>
          </div>

          {/* Features Comparison: Static QR vs URPASS Dynamic QR */}
          <div className="mt-16 bg-white rounded-3xl border border-neutral-200 overflow-hidden shadow-xs">
            <div className="p-6 border-b border-neutral-100 bg-neutral-50/50">
              <h2 className="text-lg font-bold text-neutral-900">Static Generic QR vs URPASS Cryptographic Passes</h2>
              <p className="text-xs text-neutral-500 mt-0.5">Why simple QR generator websites cause door chaos at real events.</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-neutral-50 text-neutral-500 uppercase tracking-wider font-semibold border-b border-neutral-200">
                  <tr>
                    <th className="py-3.5 px-5">Capability</th>
                    <th className="py-3.5 px-5">URPASS Dynamic Passes</th>
                    <th className="py-3.5 px-5">Generic Static QR Generators</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-100 text-neutral-700">
                  <tr className="bg-emerald-50/30 font-semibold text-neutral-900">
                    <td className="py-4 px-5 text-emerald-700 flex items-center gap-1.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                      Duplicate Entry Prevention
                    </td>
                    <td className="py-4 px-5 font-bold text-emerald-700">Atomic real-time lock across all gates</td>
                    <td className="py-4 px-5 text-rose-600">None (can be shared and scanned endlessly)</td>
                  </tr>
                  <tr>
                    <td className="py-4 px-5 font-medium">Door Check-In Velocity</td>
                    <td className="py-4 px-5">Sub-0.3s camera scan with audio confirmation</td>
                    <td className="py-4 px-5">Manual spreadsheet search required</td>
                  </tr>
                  <tr>
                    <td className="py-4 px-5 font-medium">Offline Gate Reliability</td>
                    <td className="py-4 px-5">IndexedDB cache keeps scanning during network drops</td>
                    <td className="py-4 px-5">Fails without active web link resolution</td>
                  </tr>
                  <tr>
                    <td className="py-4 px-5 font-medium">Automated Delivery</td>
                    <td className="py-4 px-5">Instant transactional email + WhatsApp link</td>
                    <td className="py-4 px-5">Must manually copy and paste images</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* FAQs */}
          <div className="mt-20">
            <h2 className="text-2xl font-black text-neutral-950 text-center mb-8">
              Frequently Asked Questions
            </h2>
            <div className="space-y-4 max-w-3xl mx-auto">
              {FAQS.map((faq, idx) => (
                <div key={idx} className="bg-white border border-neutral-200 rounded-2xl p-5 shadow-xs">
                  <h3 className="text-sm font-bold text-neutral-900">{faq.q}</h3>
                  <p className="text-xs text-neutral-600 mt-2 leading-relaxed">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Bottom Conversion CTA */}
          <div className="mt-20 bg-gradient-to-br from-neutral-900 to-violet-950 rounded-3xl p-8 sm:p-12 text-center text-white shadow-xl">
            <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
              Ready to generate real passes for your attendees?
            </h2>
            <p className="mt-3 text-neutral-300 text-xs sm:text-sm max-w-xl mx-auto leading-relaxed">
              Launch your event registration on URPASS today. Permanent free tier available with zero setup fees.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href="/signup?ref=free-qr-cta"
                className="w-full sm:w-auto px-6 py-3.5 rounded-xl bg-white hover:bg-neutral-100 text-neutral-950 font-bold text-sm transition-all shadow-md"
              >
                Create Your Free Event Now →
              </Link>
              <Link
                href="/pricing"
                className="w-full sm:w-auto px-6 py-3.5 rounded-xl bg-white/10 hover:bg-white/20 text-white font-semibold text-sm transition-all border border-white/20"
              >
                Explore Pricing Plans
              </Link>
            </div>
            <p className="text-[11px] text-neutral-400 mt-4">
              ₹0 forever free tier · No credit card required · Instant mobile scanner
            </p>
          </div>
        </section>
      </div>

      <Footer />
    </div>
  );
}
