import type { StudioDesign, TicketFormat } from "./types";

export interface StudioTemplateDefinition {
  id: string;
  name: string;
  category: "Minimal" | "Concert" | "Corporate" | "College" | "Conference" | "Hackathon" | "VIP" | "Workshop" | "Sports" | "Exhibition" | "Community" | "Luxury";
  format: TicketFormat;
  description: string;
  tags: string[];
  thumbnailBg: string;
  design: StudioDesign;
}

export const STUDIO_TEMPLATES: StudioTemplateDefinition[] = [
  // 1. Minimal Monochrome (Digital Pass)
  {
    id: "minimal-monochrome",
    name: "Minimal Monochrome",
    category: "Minimal",
    format: "digital",
    description: "Crisp black and white editorial typography with high contrast and centered QR.",
    tags: ["Minimal", "Clean", "Editorial", "Monochrome"],
    thumbnailBg: "#FFFFFF",
    design: {
      version: 2,
      format: "digital",
      width: 380,
      height: 680,
      name: "Minimal Monochrome",
      isPublished: true,
      background: {
        type: "color",
        color: "#FFFFFF",
      },
      elements: [
        {
          id: "m-badge",
          type: "shape",
          name: "Badge Container",
          shapeType: "pill",
          x: 100,
          y: 32,
          width: 180,
          height: 28,
          fillColor: "#F4F4F5",
          borderColor: "#E4E4E7",
          borderWidth: 1,
          borderRadius: 999,
          zIndex: 1,
        },
        {
          id: "m-header",
          type: "text",
          name: "Header Badge",
          content: "OFFICIAL ENTRY PASS",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#71717A",
          textAlign: "center",
          letterSpacing: 2,
          textTransform: "uppercase",
          x: 100,
          y: 39,
          width: 180,
          height: 18,
          zIndex: 2,
        },
        {
          id: "m-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "URPASS TECH SUMMIT 2026",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#18181B",
          textAlign: "center",
          letterSpacing: -0.5,
          textTransform: "uppercase",
          x: 20,
          y: 76,
          width: 340,
          height: 36,
          zIndex: 3,
        },
        {
          id: "m-event-date",
          type: "dynamic_text",
          name: "Event Date & Venue",
          fieldKey: "event.date",
          fallbackText: "24 OCT 2026 · THE RESIDENCY",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 600,
          color: "#71717A",
          textAlign: "center",
          letterSpacing: 1,
          textTransform: "uppercase",
          x: 20,
          y: 118,
          width: 340,
          height: 20,
          zIndex: 4,
        },
        {
          id: "m-div-1",
          type: "divider",
          name: "Top Divider",
          color: "#E4E4E7",
          thickness: 1,
          style: "solid",
          x: 24,
          y: 154,
          width: 332,
          height: 1,
          zIndex: 5,
        },
        {
          id: "m-qr",
          type: "qr",
          name: "Entry QR Code",
          size: 190,
          fgColor: "#09090B",
          bgColor: "#FFFFFF",
          cornerRadius: 12,
          showScanLabel: true,
          scanLabelText: "SCAN AT ENTRANCE",
          showAttendeeId: true,
          contrastSafe: true,
          x: 95,
          y: 180,
          width: 190,
          height: 190,
          locked: true,
          zIndex: 6,
        },
        {
          id: "m-div-2",
          type: "divider",
          name: "Bottom Divider",
          color: "#E4E4E7",
          thickness: 1,
          style: "solid",
          x: 24,
          y: 430,
          width: 332,
          height: 1,
          zIndex: 7,
        },
        {
          id: "m-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#09090B",
          textAlign: "center",
          letterSpacing: -0.2,
          textTransform: "uppercase",
          x: 20,
          y: 450,
          width: 340,
          height: 30,
          zIndex: 8,
        },
        {
          id: "m-ticket-category",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "VIP ACCESS",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 700,
          color: "#18181B",
          textAlign: "center",
          letterSpacing: 2,
          textTransform: "uppercase",
          x: 20,
          y: 490,
          width: 340,
          height: 20,
          zIndex: 9,
        },
        {
          id: "m-ticket-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 600,
          color: "#A1A1AA",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 520,
          width: 340,
          height: 20,
          zIndex: 10,
        },
        {
          id: "m-footer",
          type: "text",
          name: "Footer Note",
          content: "Valid for one entry only · Non-transferable",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 500,
          color: "#A1A1AA",
          textAlign: "center",
          x: 20,
          y: 630,
          width: 340,
          height: 18,
          zIndex: 11,
        },
      ],
    },
  },

  // 2. Concert & Music Fest (Printable Landscape Ticket)
  {
    id: "concert-music-fest",
    name: "Concert & Music Fest",
    category: "Concert",
    format: "printable",
    description: "Cyberpunk neon dark ticket with perforated stub tear line and VIP stage tags.",
    tags: ["Concert", "Music", "Nightlife", "Neon", "Printable"],
    thumbnailBg: "#0F0F1A",
    design: {
      version: 2,
      format: "printable",
      width: 780,
      height: 340,
      name: "Concert & Music Fest",
      isPublished: true,
      background: {
        type: "color",
        color: "#0D0D14",
      },
      elements: [
        {
          id: "c-left-accent",
          type: "shape",
          name: "Left Neon Ribbon",
          shapeType: "rect",
          x: 0,
          y: 0,
          width: 8,
          height: 340,
          fillColor: "#EC4899",
          zIndex: 1,
        },
        {
          id: "c-tag",
          type: "text",
          name: "Live Tour Tag",
          content: "LIVE IN CONCERT // WORLD TOUR 2026",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#EC4899",
          textAlign: "left",
          letterSpacing: 2,
          x: 32,
          y: 28,
          width: 480,
          height: 18,
          zIndex: 2,
        },
        {
          id: "c-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "NEON HORIZON FESTIVAL",
          fontFamily: "sans",
          fontSize: 26,
          fontWeight: 900,
          color: "#FFFFFF",
          textAlign: "left",
          letterSpacing: -0.5,
          textTransform: "uppercase",
          x: 32,
          y: 56,
          width: 480,
          height: 40,
          zIndex: 3,
        },
        {
          id: "c-date",
          type: "dynamic_text",
          name: "Date & Time",
          fieldKey: "event.date",
          fallbackText: "24 OCT 2026 · GATES OPEN 6:00 PM",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 700,
          color: "#A78BFA",
          textAlign: "left",
          letterSpacing: 1,
          x: 32,
          y: 104,
          width: 480,
          height: 20,
          zIndex: 4,
        },
        {
          id: "c-venue",
          type: "dynamic_text",
          name: "Venue",
          fieldKey: "event.venue",
          fallbackText: "JLN Arena, Chennai",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 500,
          color: "#9CA3AF",
          textAlign: "left",
          x: 32,
          y: 130,
          width: 480,
          height: 20,
          zIndex: 5,
        },
        {
          id: "c-attendee-card",
          type: "shape",
          name: "Attendee Info Box",
          shapeType: "rect",
          x: 32,
          y: 175,
          width: 490,
          height: 120,
          fillColor: "#1A1A26",
          borderColor: "#2E2E40",
          borderWidth: 1,
          borderRadius: 12,
          zIndex: 6,
        },
        {
          id: "c-att-name-label",
          type: "text",
          name: "Attendee Label",
          content: "PASS HOLDER",
          fontFamily: "sans",
          fontSize: 9,
          fontWeight: 700,
          color: "#6B7280",
          textAlign: "left",
          letterSpacing: 1.5,
          x: 52,
          y: 195,
          width: 200,
          height: 16,
          zIndex: 7,
        },
        {
          id: "c-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "left",
          x: 52,
          y: 216,
          width: 280,
          height: 26,
          zIndex: 8,
        },
        {
          id: "c-zone",
          type: "dynamic_text",
          name: "Zone",
          fieldKey: "ticket.zone",
          fallbackText: "ZONE A · FRONT ROW STANDING",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 700,
          color: "#34D399",
          textAlign: "left",
          x: 52,
          y: 254,
          width: 320,
          height: 20,
          zIndex: 9,
        },
        {
          id: "c-stub-divider",
          type: "divider",
          name: "Perforated Stub Divider",
          color: "#374151",
          thickness: 2,
          style: "dashed",
          x: 550,
          y: 0,
          width: 2,
          height: 340,
          zIndex: 10,
        },
        {
          id: "c-stub-title",
          type: "text",
          name: "Stub Title",
          content: "ADMIT ONE",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 800,
          color: "#EC4899",
          textAlign: "center",
          letterSpacing: 3,
          x: 570,
          y: 24,
          width: 190,
          height: 18,
          zIndex: 11,
        },
        {
          id: "c-qr",
          type: "qr",
          name: "Ticket QR",
          size: 160,
          fgColor: "#000000",
          bgColor: "#FFFFFF",
          cornerRadius: 8,
          showScanLabel: true,
          scanLabelText: "SCAN AT GATE",
          contrastSafe: true,
          x: 585,
          y: 54,
          width: 160,
          height: 160,
          locked: true,
          zIndex: 12,
        },
        {
          id: "c-ticket-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#9CA3AF",
          textAlign: "center",
          x: 570,
          y: 285,
          width: 190,
          height: 18,
          zIndex: 13,
        },
      ],
    },
  },

  // 3. Corporate Summit & Gala (Digital Pass)
  {
    id: "corporate-summit-gala",
    name: "Corporate Summit & Gala",
    category: "Corporate",
    format: "digital",
    description: "Deep executive navy blue and gold accents tailored for leadership symposiums.",
    tags: ["Corporate", "Executive", "Gold", "Summit", "Professional"],
    thumbnailBg: "#0B132B",
    design: {
      version: 2,
      format: "digital",
      width: 380,
      height: 680,
      name: "Corporate Summit & Gala",
      isPublished: true,
      background: {
        type: "color",
        color: "#0B132B",
      },
      elements: [
        {
          id: "corp-gold-bar",
          type: "shape",
          name: "Gold Header Ribbon",
          shapeType: "rect",
          x: 0,
          y: 0,
          width: 380,
          height: 6,
          fillColor: "#F59E0B",
          zIndex: 1,
        },
        {
          id: "corp-label",
          type: "text",
          name: "Leadership Series",
          content: "EXECUTIVE LEADERSHIP SUMMIT",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#F59E0B",
          textAlign: "center",
          letterSpacing: 2,
          x: 20,
          y: 36,
          width: 340,
          height: 18,
          zIndex: 2,
        },
        {
          id: "corp-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "GLOBAL INNOVATION FORUM 2026",
          fontFamily: "sans",
          fontSize: 18,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: -0.3,
          textTransform: "uppercase",
          x: 20,
          y: 68,
          width: 340,
          height: 38,
          zIndex: 3,
        },
        {
          id: "corp-date-venue",
          type: "dynamic_text",
          name: "Date & Venue",
          fieldKey: "event.venue",
          fallbackText: "24 OCT 2026 · THE LEELA PALACE, BENGALURU",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 600,
          color: "#94A3B8",
          textAlign: "center",
          letterSpacing: 0.5,
          x: 20,
          y: 116,
          width: 340,
          height: 20,
          zIndex: 4,
        },
        {
          id: "corp-qr-card",
          type: "shape",
          name: "QR Container Card",
          shapeType: "rect",
          x: 75,
          y: 165,
          width: 230,
          height: 230,
          fillColor: "#FFFFFF",
          borderColor: "#F59E0B",
          borderWidth: 1,
          borderRadius: 16,
          zIndex: 5,
        },
        {
          id: "corp-qr",
          type: "qr",
          name: "Verification QR",
          size: 180,
          fgColor: "#0B132B",
          bgColor: "#FFFFFF",
          cornerRadius: 6,
          showScanLabel: true,
          scanLabelText: "SCAN AT EXECUTIVE DESK",
          contrastSafe: true,
          x: 100,
          y: 190,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 6,
        },
        {
          id: "corp-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          x: 20,
          y: 430,
          width: 340,
          height: 30,
          zIndex: 7,
        },
        {
          id: "corp-company",
          type: "dynamic_text",
          name: "Company",
          fieldKey: "attendee.company",
          fallbackText: "Stripe India · Staff Architect",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 500,
          color: "#CBD5E1",
          textAlign: "center",
          x: 20,
          y: 468,
          width: 340,
          height: 20,
          zIndex: 8,
        },
        {
          id: "corp-tier-pill",
          type: "shape",
          name: "Tier Container",
          shapeType: "pill",
          x: 110,
          y: 504,
          width: 160,
          height: 28,
          fillColor: "#F59E0B20",
          borderColor: "#F59E0B60",
          borderWidth: 1,
          borderRadius: 999,
          zIndex: 9,
        },
        {
          id: "corp-tier",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "EXECUTIVE DELEGATE",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#F59E0B",
          textAlign: "center",
          letterSpacing: 1.5,
          textTransform: "uppercase",
          x: 110,
          y: 510,
          width: 160,
          height: 18,
          zIndex: 10,
        },
        {
          id: "corp-id",
          type: "dynamic_text",
          name: "Pass ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#64748B",
          textAlign: "center",
          x: 20,
          y: 630,
          width: 340,
          height: 18,
          zIndex: 11,
        },
      ],
    },
  },

  // 4. College Fest & Culturals (Event Badge)
  {
    id: "college-fest-badge",
    name: "College Fest & Culturals",
    category: "College",
    format: "badge",
    description: "Vibrant purple-pink student lanyard badge with prominent college and attendee credentials.",
    tags: ["College", "Fest", "Campus", "Badge", "Students"],
    thumbnailBg: "#6366F1",
    design: {
      version: 2,
      format: "badge",
      width: 440,
      height: 640,
      name: "College Fest & Culturals",
      isPublished: true,
      background: {
        type: "color",
        color: "#4F46E5",
      },
      elements: [
        {
          id: "col-lanyard-notch",
          type: "shape",
          name: "Lanyard Slot Hole",
          shapeType: "pill",
          x: 190,
          y: 18,
          width: 60,
          height: 12,
          fillColor: "#312E81",
          borderRadius: 999,
          zIndex: 1,
        },
        {
          id: "col-header",
          type: "text",
          name: "College Banner",
          content: "NATIONAL INTER-COLLEGE FEST",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#C7D2FE",
          textAlign: "center",
          letterSpacing: 2,
          x: 20,
          y: 44,
          width: 400,
          height: 18,
          zIndex: 2,
        },
        {
          id: "col-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "DHVANI 2026",
          fontFamily: "sans",
          fontSize: 28,
          fontWeight: 900,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 72,
          width: 400,
          height: 42,
          zIndex: 3,
        },
        {
          id: "col-card",
          type: "shape",
          name: "Badge Body Card",
          shapeType: "rect",
          x: 24,
          y: 130,
          width: 392,
          height: 470,
          fillColor: "#FFFFFF",
          borderRadius: 20,
          zIndex: 4,
        },
        {
          id: "col-att-name",
          type: "dynamic_text",
          name: "Student Name",
          fieldKey: "attendee.name",
          fallbackText: "ANANYA RAMESH",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 800,
          color: "#1E1B4B",
          textAlign: "center",
          letterSpacing: -0.2,
          x: 40,
          y: 160,
          width: 360,
          height: 32,
          zIndex: 5,
        },
        {
          id: "col-college",
          type: "dynamic_text",
          name: "College / Org",
          fieldKey: "attendee.company",
          fallbackText: "PSG College of Technology",
          fontFamily: "sans",
          fontSize: 13,
          fontWeight: 600,
          color: "#4F46E5",
          textAlign: "center",
          x: 40,
          y: 198,
          width: 360,
          height: 22,
          zIndex: 6,
        },
        {
          id: "col-qr",
          type: "qr",
          name: "Badge QR Code",
          size: 175,
          fgColor: "#1E1B4B",
          bgColor: "#FFFFFF",
          cornerRadius: 12,
          showScanLabel: true,
          scanLabelText: "SCAN FOR CAMPUS ENTRY",
          contrastSafe: true,
          x: 132,
          y: 236,
          width: 175,
          height: 175,
          locked: true,
          zIndex: 7,
        },
        {
          id: "col-tier-badge",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "STUDENT DELEGATE",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 800,
          color: "#4338CA",
          textAlign: "center",
          letterSpacing: 2,
          x: 40,
          y: 448,
          width: 360,
          height: 24,
          zIndex: 8,
        },
        {
          id: "col-zone",
          type: "dynamic_text",
          name: "Access Zone",
          fieldKey: "ticket.zone",
          fallbackText: "CAMPUS ENTRY · MAIN AUDITORIUM",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#6B7280",
          textAlign: "center",
          x: 40,
          y: 480,
          width: 360,
          height: 18,
          zIndex: 9,
        },
        {
          id: "col-ticket-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10287",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#9CA3AF",
          textAlign: "center",
          x: 40,
          y: 550,
          width: 360,
          height: 18,
          zIndex: 10,
        },
      ],
    },
  },

  // 5. Tech Conference & Keynote (Event Badge)
  {
    id: "tech-conf-badge",
    name: "Tech Conference & Keynote",
    category: "Conference",
    format: "badge",
    description: "Modern dark slate badge layout for engineering summits and keynote talks.",
    tags: ["Tech", "Conference", "Developer", "Badge", "Keynote"],
    thumbnailBg: "#0F172A",
    design: {
      version: 2,
      format: "badge",
      width: 440,
      height: 640,
      name: "Tech Conference & Keynote",
      isPublished: true,
      background: {
        type: "color",
        color: "#0F172A",
      },
      elements: [
        {
          id: "tc-lanyard-notch",
          type: "shape",
          name: "Lanyard Slot Hole",
          shapeType: "pill",
          x: 190,
          y: 18,
          width: 60,
          height: 12,
          fillColor: "#020617",
          borderRadius: 999,
          zIndex: 1,
        },
        {
          id: "tc-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "DEVCONF INDIA 2026",
          fontFamily: "sans",
          fontSize: 18,
          fontWeight: 900,
          color: "#38BDF8",
          textAlign: "center",
          letterSpacing: 2,
          x: 20,
          y: 52,
          width: 400,
          height: 26,
          zIndex: 2,
        },
        {
          id: "tc-att-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 26,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: -0.3,
          x: 20,
          y: 110,
          width: 400,
          height: 38,
          zIndex: 3,
        },
        {
          id: "tc-company",
          type: "dynamic_text",
          name: "Company & Role",
          fieldKey: "attendee.company",
          fallbackText: "Stripe India",
          fontFamily: "sans",
          fontSize: 14,
          fontWeight: 600,
          color: "#94A3B8",
          textAlign: "center",
          x: 20,
          y: 154,
          width: 400,
          height: 22,
          zIndex: 4,
        },
        {
          id: "tc-tier-pill",
          type: "shape",
          name: "Tier Container",
          shapeType: "pill",
          x: 130,
          y: 194,
          width: 180,
          height: 32,
          fillColor: "#0EA5E915",
          borderColor: "#38BDF8",
          borderWidth: 1.5,
          borderRadius: 999,
          zIndex: 5,
        },
        {
          id: "tc-tier",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "KEYNOTE SPEAKER",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 800,
          color: "#38BDF8",
          textAlign: "center",
          letterSpacing: 2,
          x: 130,
          y: 202,
          width: 180,
          height: 18,
          zIndex: 6,
        },
        {
          id: "tc-qr-card",
          type: "shape",
          name: "QR Container",
          shapeType: "rect",
          x: 115,
          y: 250,
          width: 210,
          height: 210,
          fillColor: "#FFFFFF",
          borderRadius: 16,
          zIndex: 7,
        },
        {
          id: "tc-qr",
          type: "qr",
          name: "Check-in QR",
          size: 180,
          fgColor: "#0F172A",
          bgColor: "#FFFFFF",
          cornerRadius: 6,
          showScanLabel: true,
          scanLabelText: "SCAN AT SPEED-GATE",
          contrastSafe: true,
          x: 130,
          y: 265,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 8,
        },
        {
          id: "tc-zone",
          type: "dynamic_text",
          name: "Access Zone",
          fieldKey: "ticket.zone",
          fallbackText: "ALL STAGES + GREEN ROOM",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#38BDF8",
          textAlign: "center",
          x: 20,
          y: 490,
          width: 400,
          height: 18,
          zIndex: 9,
        },
        {
          id: "tc-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10286",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 600,
          color: "#64748B",
          textAlign: "center",
          x: 20,
          y: 585,
          width: 400,
          height: 18,
          zIndex: 10,
        },
      ],
    },
  },

  // 6. Hackathon Terminal (Digital Pass)
  {
    id: "hackathon-terminal",
    name: "Hackathon Terminal",
    category: "Hackathon",
    format: "digital",
    description: "Cyber hacker terminal aesthetic with neon emerald monospace code blocks.",
    tags: ["Hackathon", "Hacker", "Code", "Terminal", "Emerald"],
    thumbnailBg: "#0B1015",
    design: {
      version: 2,
      format: "digital",
      width: 380,
      height: 680,
      name: "Hackathon Terminal",
      isPublished: true,
      background: {
        type: "color",
        color: "#080C0E",
      },
      elements: [
        {
          id: "h-bar",
          type: "shape",
          name: "Terminal Title Bar",
          shapeType: "rect",
          x: 16,
          y: 18,
          width: 348,
          height: 28,
          fillColor: "#11181C",
          borderRadius: 8,
          zIndex: 1,
        },
        {
          id: "h-sys-title",
          type: "text",
          name: "Terminal Title",
          content: "● ● ●  hack://build.urpass/auth",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#10B981",
          textAlign: "left",
          x: 28,
          y: 25,
          width: 320,
          height: 16,
          zIndex: 2,
        },
        {
          id: "h-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "ETHGLOBAL HACKATHON 2026",
          fontFamily: "mono",
          fontSize: 16,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 65,
          width: 340,
          height: 28,
          zIndex: 3,
        },
        {
          id: "h-sprint",
          type: "text",
          name: "Sprint Details",
          content: "[ 36-HOUR NON-STOP SPRINT ]",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#10B981",
          textAlign: "center",
          letterSpacing: 2,
          x: 20,
          y: 100,
          width: 340,
          height: 18,
          zIndex: 4,
        },
        {
          id: "h-qr-frame",
          type: "shape",
          name: "QR Container Frame",
          shapeType: "rect",
          x: 75,
          y: 140,
          width: 230,
          height: 230,
          fillColor: "#FFFFFF",
          borderColor: "#10B981",
          borderWidth: 2,
          borderRadius: 16,
          zIndex: 5,
        },
        {
          id: "h-qr",
          type: "qr",
          name: "Hacker QR",
          size: 180,
          fgColor: "#052E16",
          bgColor: "#FFFFFF",
          cornerRadius: 4,
          showScanLabel: true,
          scanLabelText: "CHECK-IN GATE TOKEN",
          contrastSafe: true,
          x: 100,
          y: 165,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 6,
        },
        {
          id: "h-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "mono",
          fontSize: 20,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          x: 20,
          y: 400,
          width: 340,
          height: 28,
          zIndex: 7,
        },
        {
          id: "h-role",
          type: "text",
          name: "Builder Role",
          content: "> ROLE: VERIFIED_BUILDER",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 700,
          color: "#10B981",
          textAlign: "center",
          x: 20,
          y: 438,
          width: 340,
          height: 20,
          zIndex: 8,
        },
        {
          id: "h-track",
          type: "text",
          name: "Track",
          content: "TRACK: AI AGENTS & APIS",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#6EE7B7",
          textAlign: "center",
          x: 20,
          y: 466,
          width: 340,
          height: 18,
          zIndex: 9,
        },
        {
          id: "h-ticket-id",
          type: "dynamic_text",
          name: "Token ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#4B5563",
          textAlign: "center",
          x: 20,
          y: 625,
          width: 340,
          height: 18,
          zIndex: 10,
        },
      ],
    },
  },

  // 7. VIP All-Access Pass (Event Badge)
  {
    id: "vip-all-access",
    name: "VIP All-Access Pass",
    category: "VIP",
    format: "badge",
    description: "Gold and obsidian luxury badge designed for VIP lounges and security checkpoints.",
    tags: ["VIP", "Luxury", "Gold", "Obsidian", "All-Access"],
    thumbnailBg: "#18181B",
    design: {
      version: 2,
      format: "badge",
      width: 440,
      height: 640,
      name: "VIP All-Access Pass",
      isPublished: true,
      background: {
        type: "color",
        color: "#141417",
      },
      elements: [
        {
          id: "v-lanyard-notch",
          type: "shape",
          name: "Lanyard Slot Hole",
          shapeType: "pill",
          x: 190,
          y: 18,
          width: 60,
          height: 12,
          fillColor: "#27272A",
          borderRadius: 999,
          zIndex: 1,
        },
        {
          id: "v-gold-bar",
          type: "shape",
          name: "Gold Foil Banner",
          shapeType: "pill",
          x: 95,
          y: 46,
          width: 250,
          height: 28,
          fillColor: "#F59E0B",
          borderRadius: 999,
          zIndex: 2,
        },
        {
          id: "v-badge-label",
          type: "text",
          name: "VIP Label",
          content: "★ VIP ALL-ACCESS PASS ★",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 900,
          color: "#000000",
          textAlign: "center",
          letterSpacing: 2,
          x: 95,
          y: 52,
          width: 250,
          height: 18,
          zIndex: 3,
        },
        {
          id: "v-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "FOUNDERS SYMPOSIUM 2026",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: 0.5,
          x: 20,
          y: 95,
          width: 400,
          height: 32,
          zIndex: 4,
        },
        {
          id: "v-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "PRIYA SHARMA",
          fontFamily: "sans",
          fontSize: 26,
          fontWeight: 900,
          color: "#FBBF24",
          textAlign: "center",
          x: 20,
          y: 145,
          width: 400,
          height: 36,
          zIndex: 5,
        },
        {
          id: "v-company",
          type: "dynamic_text",
          name: "Company",
          fieldKey: "attendee.company",
          fallbackText: "Razorpay · Managing Director",
          fontFamily: "sans",
          fontSize: 13,
          fontWeight: 600,
          color: "#D1D5DB",
          textAlign: "center",
          x: 20,
          y: 188,
          width: 400,
          height: 20,
          zIndex: 6,
        },
        {
          id: "v-qr-card",
          type: "shape",
          name: "Gold QR Frame",
          shapeType: "rect",
          x: 120,
          y: 230,
          width: 200,
          height: 200,
          fillColor: "#FFFFFF",
          borderColor: "#F59E0B",
          borderWidth: 2,
          borderRadius: 16,
          zIndex: 7,
        },
        {
          id: "v-qr",
          type: "qr",
          name: "VIP Security QR",
          size: 170,
          fgColor: "#18181B",
          bgColor: "#FFFFFF",
          cornerRadius: 6,
          showScanLabel: true,
          scanLabelText: "PRIORITY CHECK-IN",
          contrastSafe: true,
          x: 135,
          y: 245,
          width: 170,
          height: 170,
          locked: true,
          zIndex: 8,
        },
        {
          id: "v-zone",
          type: "dynamic_text",
          name: "Access Zone",
          fieldKey: "ticket.zone",
          fallbackText: "STAGE ACCESS · PRIVATE LOUNGE",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 800,
          color: "#F59E0B",
          textAlign: "center",
          x: 20,
          y: 458,
          width: 400,
          height: 20,
          zIndex: 9,
        },
        {
          id: "v-ticket-id",
          type: "dynamic_text",
          name: "Security ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10285",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 600,
          color: "#71717A",
          textAlign: "center",
          x: 20,
          y: 580,
          width: 400,
          height: 18,
          zIndex: 10,
        },
      ],
    },
  },

  // 8. Workshop & Masterclass (Printable Landscape Ticket)
  {
    id: "workshop-masterclass",
    name: "Workshop & Masterclass",
    category: "Workshop",
    format: "printable",
    description: "Warm terracotta and cream editorial certificate pass for hands-on bootcamps.",
    tags: ["Workshop", "Education", "Bootcamp", "Warm", "Printable"],
    thumbnailBg: "#FAF5F0",
    design: {
      version: 2,
      format: "printable",
      width: 780,
      height: 340,
      name: "Workshop & Masterclass",
      isPublished: true,
      background: {
        type: "color",
        color: "#FAF5F0",
      },
      elements: [
        {
          id: "w-accent-line",
          type: "shape",
          name: "Terracotta Strip",
          shapeType: "rect",
          x: 0,
          y: 0,
          width: 780,
          height: 8,
          fillColor: "#EA580C",
          zIndex: 1,
        },
        {
          id: "w-category",
          type: "text",
          name: "Category Label",
          content: "CERTIFIED HANDS-ON MASTERCLASS",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#EA580C",
          textAlign: "left",
          letterSpacing: 2,
          x: 36,
          y: 28,
          width: 480,
          height: 18,
          zIndex: 2,
        },
        {
          id: "w-event-name",
          type: "dynamic_text",
          name: "Course Title",
          fieldKey: "event.name",
          fallbackText: "BUILDING PRODUCTION AI AGENTS",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 800,
          color: "#292524",
          textAlign: "left",
          x: 36,
          y: 56,
          width: 480,
          height: 36,
          zIndex: 3,
        },
        {
          id: "w-date-time",
          type: "dynamic_text",
          name: "Date & Time",
          fieldKey: "event.date",
          fallbackText: "24 OCT 2026 · 10:00 AM - 5:00 PM",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 600,
          color: "#78716C",
          textAlign: "left",
          x: 36,
          y: 100,
          width: 480,
          height: 20,
          zIndex: 4,
        },
        {
          id: "w-venue",
          type: "dynamic_text",
          name: "Venue",
          fieldKey: "event.venue",
          fallbackText: "Innovate Labs, Coimbatore",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 500,
          color: "#78716C",
          textAlign: "left",
          x: 36,
          y: 125,
          width: 480,
          height: 20,
          zIndex: 5,
        },
        {
          id: "w-att-box",
          type: "shape",
          name: "Participant Card",
          shapeType: "rect",
          x: 36,
          y: 170,
          width: 480,
          height: 125,
          fillColor: "#FFFFFF",
          borderColor: "#E7E5E4",
          borderWidth: 1,
          borderRadius: 12,
          zIndex: 6,
        },
        {
          id: "w-att-label",
          type: "text",
          name: "Participant Label",
          content: "REGISTERED PARTICIPANT",
          fontFamily: "sans",
          fontSize: 9,
          fontWeight: 800,
          color: "#A8A29E",
          textAlign: "left",
          letterSpacing: 1.5,
          x: 56,
          y: 190,
          width: 200,
          height: 16,
          zIndex: 7,
        },
        {
          id: "w-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#1C1917",
          textAlign: "left",
          x: 56,
          y: 212,
          width: 260,
          height: 28,
          zIndex: 8,
        },
        {
          id: "w-seat",
          type: "dynamic_text",
          name: "Workstation",
          fieldKey: "ticket.seat",
          fallbackText: "WORKSTATION #14 · LAB B",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 700,
          color: "#EA580C",
          textAlign: "left",
          x: 56,
          y: 250,
          width: 260,
          height: 20,
          zIndex: 9,
        },
        {
          id: "w-divider",
          type: "divider",
          name: "Stub Divider",
          color: "#D6D3D1",
          thickness: 2,
          style: "dashed",
          x: 546,
          y: 0,
          width: 2,
          height: 340,
          zIndex: 10,
        },
        {
          id: "w-stub-title",
          type: "text",
          name: "Stub Title",
          content: "GATE PASS",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 800,
          color: "#EA580C",
          textAlign: "center",
          letterSpacing: 2,
          x: 565,
          y: 26,
          width: 200,
          height: 18,
          zIndex: 11,
        },
        {
          id: "w-qr",
          type: "qr",
          name: "Checkin QR",
          size: 160,
          fgColor: "#1C1917",
          bgColor: "#FFFFFF",
          cornerRadius: 8,
          showScanLabel: true,
          scanLabelText: "SCAN AT RECEPTION",
          contrastSafe: true,
          x: 585,
          y: 56,
          width: 160,
          height: 160,
          locked: true,
          zIndex: 12,
        },
        {
          id: "w-ticket-id",
          type: "dynamic_text",
          name: "Pass ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#78716C",
          textAlign: "center",
          x: 565,
          y: 288,
          width: 200,
          height: 18,
          zIndex: 13,
        },
      ],
    },
  },

  // 9. Sports & Arena Ticket (Printable Landscape Ticket)
  {
    id: "sports-arena-ticket",
    name: "Sports & Arena Ticket",
    category: "Sports",
    format: "printable",
    description: "Athletic bold red & charcoal arena ticket with Gate, Row, and Seat indicators.",
    tags: ["Sports", "Arena", "Stadium", "Athletic", "Printable"],
    thumbnailBg: "#991B1B",
    design: {
      version: 2,
      format: "printable",
      width: 780,
      height: 340,
      name: "Sports & Arena Ticket",
      isPublished: true,
      background: {
        type: "color",
        color: "#18181B",
      },
      elements: [
        {
          id: "s-accent",
          type: "shape",
          name: "Stadium Red Banner",
          shapeType: "rect",
          x: 0,
          y: 0,
          width: 540,
          height: 12,
          fillColor: "#DC2626",
          zIndex: 1,
        },
        {
          id: "s-league",
          type: "text",
          name: "League Name",
          content: "NATIONAL CHAMPIONSHIP FINALS 2026",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 900,
          color: "#EF4444",
          textAlign: "left",
          letterSpacing: 2,
          x: 32,
          y: 30,
          width: 480,
          height: 18,
          zIndex: 2,
        },
        {
          id: "s-event-name",
          type: "dynamic_text",
          name: "Match Title",
          fieldKey: "event.name",
          fallbackText: "CHENNAI TITANS VS BENGALURU FC",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 900,
          color: "#FFFFFF",
          textAlign: "left",
          x: 32,
          y: 58,
          width: 480,
          height: 34,
          zIndex: 3,
        },
        {
          id: "s-seating-box",
          type: "shape",
          name: "Seating Card",
          shapeType: "rect",
          x: 32,
          y: 110,
          width: 480,
          height: 80,
          fillColor: "#27272A",
          borderColor: "#3F3F46",
          borderWidth: 1,
          borderRadius: 12,
          zIndex: 4,
        },
        {
          id: "s-gate-label",
          type: "text",
          name: "Gate Label",
          content: "GATE",
          fontFamily: "sans",
          fontSize: 9,
          fontWeight: 700,
          color: "#A1A1AA",
          textAlign: "center",
          x: 50,
          y: 124,
          width: 120,
          height: 16,
          zIndex: 5,
        },
        {
          id: "s-gate-val",
          type: "text",
          name: "Gate Value",
          content: "GATE 3",
          fontFamily: "mono",
          fontSize: 18,
          fontWeight: 900,
          color: "#EF4444",
          textAlign: "center",
          x: 50,
          y: 144,
          width: 120,
          height: 26,
          zIndex: 6,
        },
        {
          id: "s-seat-label",
          type: "text",
          name: "Seat Label",
          content: "ROW / SEAT",
          fontFamily: "sans",
          fontSize: 9,
          fontWeight: 700,
          color: "#A1A1AA",
          textAlign: "center",
          x: 210,
          y: 124,
          width: 180,
          height: 16,
          zIndex: 7,
        },
        {
          id: "s-seat-val",
          type: "dynamic_text",
          name: "Seat Value",
          fieldKey: "ticket.seat",
          fallbackText: "ROW B · SEAT 14",
          fontFamily: "mono",
          fontSize: 18,
          fontWeight: 900,
          color: "#FFFFFF",
          textAlign: "center",
          x: 210,
          y: 144,
          width: 180,
          height: 26,
          zIndex: 8,
        },
        {
          id: "s-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 18,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "left",
          x: 32,
          y: 215,
          width: 320,
          height: 26,
          zIndex: 9,
        },
        {
          id: "s-date-venue",
          type: "dynamic_text",
          name: "Date & Venue",
          fieldKey: "event.date",
          fallbackText: "24 OCT 2026 · JAWAHARLAL NEHRU STADIUM",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 600,
          color: "#A1A1AA",
          textAlign: "left",
          x: 32,
          y: 250,
          width: 480,
          height: 20,
          zIndex: 10,
        },
        {
          id: "s-divider",
          type: "divider",
          name: "Stub Perforation",
          color: "#3F3F46",
          thickness: 2,
          style: "dashed",
          x: 540,
          y: 0,
          width: 2,
          height: 340,
          zIndex: 11,
        },
        {
          id: "s-qr",
          type: "qr",
          name: "Stadium Turnstile QR",
          size: 160,
          fgColor: "#000000",
          bgColor: "#FFFFFF",
          cornerRadius: 6,
          showScanLabel: true,
          scanLabelText: "SCAN AT TURNSTILE",
          contrastSafe: true,
          x: 575,
          y: 54,
          width: 160,
          height: 160,
          locked: true,
          zIndex: 12,
        },
        {
          id: "s-ticket-id",
          type: "dynamic_text",
          name: "Ticket Barcode ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 700,
          color: "#A1A1AA",
          textAlign: "center",
          x: 560,
          y: 285,
          width: 190,
          height: 18,
          zIndex: 13,
        },
      ],
    },
  },

  // 10. Exhibition & Trade Expo (Event Badge)
  {
    id: "exhibition-trade-expo",
    name: "Exhibition & Trade Expo",
    category: "Exhibition",
    format: "badge",
    description: "Corporate expo badge featuring visitor type, booth allocation, and attendee business details.",
    tags: ["Exhibition", "Trade", "Expo", "B2B", "Badge"],
    thumbnailBg: "#2563EB",
    design: {
      version: 2,
      format: "badge",
      width: 440,
      height: 640,
      name: "Exhibition & Trade Expo",
      isPublished: true,
      background: {
        type: "color",
        color: "#F8FAFC",
      },
      elements: [
        {
          id: "e-notch",
          type: "shape",
          name: "Lanyard Slot Hole",
          shapeType: "pill",
          x: 190,
          y: 18,
          width: 60,
          height: 12,
          fillColor: "#E2E8F0",
          borderRadius: 999,
          zIndex: 1,
        },
        {
          id: "e-header-box",
          type: "shape",
          name: "Header Bar",
          shapeType: "rect",
          x: 0,
          y: 40,
          width: 440,
          height: 54,
          fillColor: "#1D4ED8",
          zIndex: 2,
        },
        {
          id: "e-expo-name",
          type: "dynamic_text",
          name: "Expo Title",
          fieldKey: "event.name",
          fallbackText: "INDIA INDUSTRIAL AUTOMATION EXPO 2026",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 58,
          width: 400,
          height: 20,
          zIndex: 3,
        },
        {
          id: "e-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 26,
          fontWeight: 900,
          color: "#0F172A",
          textAlign: "center",
          letterSpacing: -0.5,
          x: 20,
          y: 130,
          width: 400,
          height: 36,
          zIndex: 4,
        },
        {
          id: "e-company",
          type: "dynamic_text",
          name: "Company Name",
          fieldKey: "attendee.company",
          fallbackText: "Stripe India Private Limited",
          fontFamily: "sans",
          fontSize: 14,
          fontWeight: 600,
          color: "#64748B",
          textAlign: "center",
          x: 20,
          y: 172,
          width: 400,
          height: 22,
          zIndex: 5,
        },
        {
          id: "e-tier-box",
          type: "shape",
          name: "Visitor Tier Banner",
          shapeType: "rect",
          x: 90,
          y: 215,
          width: 260,
          height: 38,
          fillColor: "#DBEAFE",
          borderColor: "#93C5FD",
          borderWidth: 1,
          borderRadius: 8,
          zIndex: 6,
        },
        {
          id: "e-tier",
          type: "dynamic_text",
          name: "Visitor Tier",
          fieldKey: "ticket.category",
          fallbackText: "TRADE VISITOR // BUYER",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 800,
          color: "#1E40AF",
          textAlign: "center",
          letterSpacing: 2,
          x: 90,
          y: 226,
          width: 260,
          height: 20,
          zIndex: 7,
        },
        {
          id: "e-qr",
          type: "qr",
          name: "Badge Scan QR",
          size: 180,
          fgColor: "#0F172A",
          bgColor: "#FFFFFF",
          cornerRadius: 8,
          showScanLabel: true,
          scanLabelText: "SCAN AT EXHIBITOR BOOTHS",
          contrastSafe: true,
          x: 130,
          y: 285,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 8,
        },
        {
          id: "e-zone",
          type: "dynamic_text",
          name: "Booth Access",
          fieldKey: "ticket.zone",
          fallbackText: "HALL 1, 2 & CONFERENCE SUITE",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 700,
          color: "#2563EB",
          textAlign: "center",
          x: 20,
          y: 520,
          width: 400,
          height: 20,
          zIndex: 9,
        },
        {
          id: "e-ticket-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 600,
          color: "#94A3B8",
          textAlign: "center",
          x: 20,
          y: 585,
          width: 400,
          height: 18,
          zIndex: 10,
        },
      ],
    },
  },

  // 11. Community Meetup (Digital Pass)
  {
    id: "community-meetup",
    name: "Community Meetup",
    category: "Community",
    format: "digital",
    description: "Friendly indigo and mint layout ideal for developer chapters and networking meetups.",
    tags: ["Community", "Meetup", "Friendly", "Networking", "Digital"],
    thumbnailBg: "#635BFF",
    design: {
      version: 2,
      format: "digital",
      width: 380,
      height: 680,
      name: "Community Meetup",
      isPublished: true,
      background: {
        type: "color",
        color: "#F8FAFC",
      },
      elements: [
        {
          id: "comm-card",
          type: "shape",
          name: "Meetup Card Container",
          shapeType: "rect",
          x: 16,
          y: 16,
          width: 348,
          height: 648,
          fillColor: "#FFFFFF",
          borderColor: "#E2E8F0",
          borderWidth: 1,
          borderRadius: 24,
          zIndex: 1,
        },
        {
          id: "comm-badge",
          type: "shape",
          name: "Meetup Pill",
          shapeType: "pill",
          x: 110,
          y: 40,
          width: 160,
          height: 26,
          fillColor: "#EEF2FF",
          borderRadius: 999,
          zIndex: 2,
        },
        {
          id: "comm-badge-label",
          type: "text",
          name: "Chapter Tag",
          content: "COMMUNITY MEETUP",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#635BFF",
          textAlign: "center",
          letterSpacing: 1.5,
          x: 110,
          y: 45,
          width: 160,
          height: 16,
          zIndex: 3,
        },
        {
          id: "comm-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "REACT & NEXT.JS DEVELOPERS",
          fontFamily: "sans",
          fontSize: 18,
          fontWeight: 800,
          color: "#0F172A",
          textAlign: "center",
          letterSpacing: -0.3,
          x: 30,
          y: 84,
          width: 320,
          height: 38,
          zIndex: 4,
        },
        {
          id: "comm-date",
          type: "dynamic_text",
          name: "Date & Time",
          fieldKey: "event.date",
          fallbackText: "24 OCT 2026 · 6:00 PM",
          fontFamily: "sans",
          fontSize: 12,
          fontWeight: 600,
          color: "#64748B",
          textAlign: "center",
          x: 30,
          y: 130,
          width: 320,
          height: 20,
          zIndex: 5,
        },
        {
          id: "comm-qr",
          type: "qr",
          name: "Pass QR",
          size: 180,
          fgColor: "#0F172A",
          bgColor: "#FFFFFF",
          cornerRadius: 12,
          showScanLabel: true,
          scanLabelText: "SHOW FOR CHECK-IN",
          contrastSafe: true,
          x: 100,
          y: 175,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 6,
        },
        {
          id: "comm-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 20,
          fontWeight: 800,
          color: "#0F172A",
          textAlign: "center",
          x: 30,
          y: 430,
          width: 320,
          height: 28,
          zIndex: 7,
        },
        {
          id: "comm-ticket-type",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "MEMBER PASS",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 700,
          color: "#635BFF",
          textAlign: "center",
          letterSpacing: 2,
          x: 30,
          y: 466,
          width: 320,
          height: 20,
          zIndex: 8,
        },
        {
          id: "comm-ticket-id",
          type: "dynamic_text",
          name: "Ticket ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 11,
          fontWeight: 600,
          color: "#94A3B8",
          textAlign: "center",
          x: 30,
          y: 600,
          width: 320,
          height: 18,
          zIndex: 9,
        },
      ],
    },
  },

  // 12. Dark Obsidian Luxury (Digital Pass)
  {
    id: "dark-obsidian-luxury",
    name: "Dark Obsidian Luxury",
    category: "Luxury",
    format: "digital",
    description: "Velvet black obsidian with bronze-gold typography for exclusive private events.",
    tags: ["Luxury", "Obsidian", "Bronze", "VIP", "Exclusive"],
    thumbnailBg: "#121214",
    design: {
      version: 2,
      format: "digital",
      width: 380,
      height: 680,
      name: "Dark Obsidian Luxury",
      isPublished: true,
      background: {
        type: "color",
        color: "#121214",
      },
      elements: [
        {
          id: "o-accent-top",
          type: "shape",
          name: "Bronze Accent Strip",
          shapeType: "rect",
          x: 0,
          y: 0,
          width: 380,
          height: 4,
          fillColor: "#D97706",
          zIndex: 1,
        },
        {
          id: "o-soiree-label",
          type: "text",
          name: "Exclusive Tag",
          content: "PRIVATE INVITATION ONLY",
          fontFamily: "sans",
          fontSize: 10,
          fontWeight: 800,
          color: "#D97706",
          textAlign: "center",
          letterSpacing: 3,
          x: 20,
          y: 36,
          width: 340,
          height: 18,
          zIndex: 2,
        },
        {
          id: "o-event-name",
          type: "dynamic_text",
          name: "Event Name",
          fieldKey: "event.name",
          fallbackText: "THE AUTUMN GALA 2026",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 72,
          width: 340,
          height: 32,
          zIndex: 3,
        },
        {
          id: "o-date-venue",
          type: "dynamic_text",
          name: "Date & Venue",
          fieldKey: "event.venue",
          fallbackText: "24 OCT 2026 · THE RESIDENCY, COIMBATORE",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 600,
          color: "#A1A1AA",
          textAlign: "center",
          letterSpacing: 1,
          x: 20,
          y: 115,
          width: 340,
          height: 20,
          zIndex: 4,
        },
        {
          id: "o-qr-frame",
          type: "shape",
          name: "QR Container",
          shapeType: "rect",
          x: 80,
          y: 165,
          width: 220,
          height: 220,
          fillColor: "#FFFFFF",
          borderColor: "#D97706",
          borderWidth: 1.5,
          borderRadius: 16,
          zIndex: 5,
        },
        {
          id: "o-qr",
          type: "qr",
          name: "VIP QR",
          size: 180,
          fgColor: "#121214",
          bgColor: "#FFFFFF",
          cornerRadius: 6,
          showScanLabel: true,
          scanLabelText: "SCAN AT CONCIERGE",
          contrastSafe: true,
          x: 100,
          y: 185,
          width: 180,
          height: 180,
          locked: true,
          zIndex: 6,
        },
        {
          id: "o-attendee-name",
          type: "dynamic_text",
          name: "Attendee Name",
          fieldKey: "attendee.name",
          fallbackText: "ARJUN KUMAR",
          fontFamily: "sans",
          fontSize: 22,
          fontWeight: 800,
          color: "#FFFFFF",
          textAlign: "center",
          x: 20,
          y: 430,
          width: 340,
          height: 30,
          zIndex: 7,
        },
        {
          id: "o-ticket-type",
          type: "dynamic_text",
          name: "Ticket Category",
          fieldKey: "ticket.category",
          fallbackText: "GUEST OF HONOR",
          fontFamily: "sans",
          fontSize: 11,
          fontWeight: 800,
          color: "#D97706",
          textAlign: "center",
          letterSpacing: 2,
          x: 20,
          y: 470,
          width: 340,
          height: 20,
          zIndex: 8,
        },
        {
          id: "o-ticket-id",
          type: "dynamic_text",
          name: "Pass ID",
          fieldKey: "ticket.id",
          fallbackText: "#URP-10284",
          fontFamily: "mono",
          fontSize: 10,
          fontWeight: 600,
          color: "#71717A",
          textAlign: "center",
          x: 20,
          y: 630,
          width: 340,
          height: 18,
          zIndex: 9,
        },
      ],
    },
  },
];

/**
 * Returns a clone of a template with fresh IDs.
 */
export function cloneTemplateDesign(template: StudioTemplateDefinition): StudioDesign {
  const cloned = JSON.parse(JSON.stringify(template.design)) as StudioDesign;
  cloned.elements = cloned.elements.map((el) => ({
    ...el,
    id: `${el.type}-${Math.random().toString(36).slice(2, 9)}`,
  }));
  return cloned;
}

/**
 * Creates a blank template design for a chosen format.
 */
export function createBlankDesign(format: TicketFormat): StudioDesign {
  switch (format) {
    case "printable":
      return {
        version: 2,
        format: "printable",
        width: 780,
        height: 340,
        name: "Untitled Printable Ticket",
        isPublished: false,
        background: { type: "color", color: "#FFFFFF" },
        elements: [
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Event Name",
            fieldKey: "event.name",
            fallbackText: "EVENT NAME",
            fontFamily: "sans",
            fontSize: 22,
            fontWeight: 800,
            color: "#111827",
            textAlign: "left",
            x: 32,
            y: 40,
            width: 460,
            height: 34,
            zIndex: 1,
          },
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Attendee Name",
            fieldKey: "attendee.name",
            fallbackText: "ATTENDEE NAME",
            fontFamily: "sans",
            fontSize: 18,
            fontWeight: 700,
            color: "#111827",
            textAlign: "left",
            x: 32,
            y: 110,
            width: 460,
            height: 28,
            zIndex: 2,
          },
          {
            id: `divider-${Math.random().toString(36).slice(2, 9)}`,
            type: "divider",
            name: "Stub Divider",
            color: "#E5E7EB",
            thickness: 2,
            style: "dashed",
            x: 540,
            y: 0,
            width: 2,
            height: 340,
            zIndex: 3,
          },
          {
            id: `qr-${Math.random().toString(36).slice(2, 9)}`,
            type: "qr",
            name: "QR Code",
            size: 160,
            fgColor: "#000000",
            bgColor: "#FFFFFF",
            cornerRadius: 8,
            showScanLabel: true,
            scanLabelText: "SCAN AT GATE",
            contrastSafe: true,
            x: 575,
            y: 70,
            width: 160,
            height: 160,
            locked: true,
            zIndex: 4,
          },
        ],
      };
    case "badge":
      return {
        version: 2,
        format: "badge",
        width: 440,
        height: 640,
        name: "Untitled Event Badge",
        isPublished: false,
        background: { type: "color", color: "#FFFFFF" },
        elements: [
          {
            id: `shape-${Math.random().toString(36).slice(2, 9)}`,
            type: "shape",
            name: "Lanyard Slot Hole",
            shapeType: "pill",
            x: 190,
            y: 18,
            width: 60,
            height: 12,
            fillColor: "#E5E7EB",
            borderRadius: 999,
            zIndex: 1,
          },
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Event Name",
            fieldKey: "event.name",
            fallbackText: "EVENT NAME",
            fontFamily: "sans",
            fontSize: 16,
            fontWeight: 800,
            color: "#635BFF",
            textAlign: "center",
            x: 20,
            y: 54,
            width: 400,
            height: 24,
            zIndex: 2,
          },
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Attendee Name",
            fieldKey: "attendee.name",
            fallbackText: "ATTENDEE NAME",
            fontFamily: "sans",
            fontSize: 24,
            fontWeight: 800,
            color: "#111827",
            textAlign: "center",
            x: 20,
            y: 110,
            width: 400,
            height: 36,
            zIndex: 3,
          },
          {
            id: `qr-${Math.random().toString(36).slice(2, 9)}`,
            type: "qr",
            name: "QR Code",
            size: 180,
            fgColor: "#000000",
            bgColor: "#FFFFFF",
            cornerRadius: 8,
            showScanLabel: true,
            scanLabelText: "SCAN AT ENTRANCE",
            contrastSafe: true,
            x: 130,
            y: 200,
            width: 180,
            height: 180,
            locked: true,
            zIndex: 4,
          },
        ],
      };
    case "digital":
    default:
      return {
        version: 2,
        format: "digital",
        width: 380,
        height: 680,
        name: "Untitled Digital Pass",
        isPublished: false,
        background: { type: "color", color: "#FFFFFF" },
        elements: [
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Event Name",
            fieldKey: "event.name",
            fallbackText: "EVENT NAME",
            fontFamily: "sans",
            fontSize: 18,
            fontWeight: 800,
            color: "#111827",
            textAlign: "center",
            x: 20,
            y: 40,
            width: 340,
            height: 30,
            zIndex: 1,
          },
          {
            id: `qr-${Math.random().toString(36).slice(2, 9)}`,
            type: "qr",
            name: "QR Code",
            size: 180,
            fgColor: "#000000",
            bgColor: "#FFFFFF",
            cornerRadius: 12,
            showScanLabel: true,
            scanLabelText: "SCAN FOR ENTRY",
            contrastSafe: true,
            x: 100,
            y: 160,
            width: 180,
            height: 180,
            locked: true,
            zIndex: 2,
          },
          {
            id: `text-${Math.random().toString(36).slice(2, 9)}`,
            type: "dynamic_text",
            name: "Attendee Name",
            fieldKey: "attendee.name",
            fallbackText: "ATTENDEE NAME",
            fontFamily: "sans",
            fontSize: 20,
            fontWeight: 800,
            color: "#111827",
            textAlign: "center",
            x: 20,
            y: 400,
            width: 340,
            height: 30,
            zIndex: 3,
          },
        ],
      };
  }
}
